#!/usr/bin/lua

local uci = require 'simple-uci'

local c = uci.cursor()

local secret = c:get("wiredigger", "mesh_vpn", "secret")

if not secret then
  c:set("wiredigger", "mesh_vpn", "secret", "generate")
  c:save("wiredigger")
end
